name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install MkDocs and Plugins
        run: pip install mkdocs mkdocs-material

      - name: Prepare Documentation Structure
        run: |
          mkdir -p docs
          mkdir -p docs/download
          mkdir -p docs/notify
          mkdir -p docs/processing
          mkdir -p docs/tools
          mkdir -p docs/upload
          cp -r documentation/download/. docs/download
          cp -r documentation/notify/. docs/notify
          cp -r documentation/processing/. docs/processing
          cp -r documentation/tools/. docs/tools
          cp -r documentation/upload/. docs/upload
          cp README.md docs/

      - name: Build MkDocs Site
        run: |
          mkdocs build
          mv site public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
