name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python (matching GitLab CI)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies (ensure mkdocs and material theme are installed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # Prepare documentation structure
      - name: Prepare Documentation Structure
        run: |
          mkdir -p docs
          mkdir -p docs/download
          mkdir -p docs/img
          mkdir -p docs/notify
          mkdir -p docs/processing
          mkdir -p docs/tools
          mkdir -p docs/upload
          cp -r documentation/download/. docs/download
          cp -r img/. docs/img
          cp -r documentation/notify/. docs/notify
          cp -r documentation/processing/. docs/processing
          cp -r documentation/tools/. docs/tools
          cp -r documentation/upload/. docs/upload
          cp README.md docs/

      # Build the MkDocs site
      - name: Build MkDocs Site
        run: mkdocs build --clean

      # Postprocess documentation structure
      - name: Postprocess Documentation Structure
        run: |
          cp -r documentation/download/. download
          cp -r documentation/notify/. notify
          cp -r documentation/processing/. processing
          cp -r documentation/tools/. tools
          cp -r documentation/upload/. upload

      # Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
